apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: nginx 
        image: docker.io/niiku/kargo-demo-app:v0.1.0
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
        env:
          - name: LOG_LEVEL
            value: "DEBUG"
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content
