apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
  - target:
      kind: Route
      name: kargo-demo
    patch: |-
      - op: replace
        path: /spec/host
        value: kargo-demo-uat.apps.baloise.dev
